version: '3.7'

services:
  hdbudgetapi:
    container_name: 'hdbudgetapi'
    image: 'evildaniel2000/hdbudgetapi'
    ports:
      - 80:5000
    depends_on:
      - "postgres"
    networks:
      - mynetwork

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    networks:
      - mynetwork

#must add network bridge in order to access it from localhost
networks:
  mynetwork:
     driver: bridge